### ISSUE TITLE
valid_url() doesn't seem to accept URLs that aren't localhost

### ISSUE THREAD

**Issue by olyerickson** [AlexIoannides/elasticsearchr#41]
We have a valid URL of the form `https://my.server.edu/elasticsearch` (note the https!) that works perfectly from the console with `curl` but which `valid_url()` claims is invalid. 

Does `elasticsearchr` accept non-localhost URLs?

Thanks!

**Comment by olyerickson** [comment]
It looks to me like you are specifically excluding non-numeric URLs:
```

valid_url <- function(url) {
  if (grepl("https?://", url) & grepl(":[0-9][0-9]+", url) & !(substr(url, nchar(url), nchar(url)) == "/")) {
    return(TRUE)
  } else {
    stop("invalid URL to Elasticsearch cluster")
  }
}
```
For a normal (and valid!) URL, this will come up `FALSE`:
```
grepl(":[0-9][0-9]+", url)
```

**Comment by olyerickson** [comment]
Our workaround is to use the (numerical) IP address of our ES instance.

**Comment by blevid2** [comment]
`
valid_url <- function(url) {
  if (grepl("https?://", url) & grepl(":[0-9][0-9]+", url) & !(substr(url, nchar(url), nchar(url)) == "/")) {
    return(TRUE)
  } else {
    stop("invalid URL to Elasticsearch cluster")
  }
}
`

As pointed out, the above function excludes valid elasticsearch URLs.  

- This statement appears to require the URL to have a port number: `grepl(":[0-9][0-9]+", url)`
- This statement excludes trailing slashes : `!(substr(url, nchar(url), nchar(url)) == "/")`

However, if you have elasticsearch behind a reverse proxy, you could have a perfectly valid URL of the form http://mywebsite.com/elasticsearch/

**Comment by AlexIoannides** [comment]
Thanks for pointing-out these issues and @blevid2 for proposing a fix.

Upon reflection, it seems to me that trying to infer valid URLs based on the strings passed to the validation function, is not optimal - better to try and reach the cluster at the provided URL and then handle any errors accordingly.

@olyerickson @blevid2 - do you have any thoughts on this, before I merge to master and submit to CRAN?

**Comment by olyerickson** [comment]
I'd go with David's approach; I've been testing it successfully all day. 

I've got other, more general thoughts on `elasticsearchr` functionality, which I'll add as issues ASAP. One of the most pressing is including outside-the-query options such as `from:` and `size:`, which are critical for exploration. Our ES database has 73478254 documents in it as of this morning, so "wide open" queries aren't practical! ;)

**Comment by AlexIoannides** [comment]
> I'd go with David's approach; I've been testing it successfully all day.

I'm not sure that's the right way to two make the comparison. My feeling is that the older approach is just bad programming.

w.r.t. `size` - you do have that. Please check the documentation for `query`. Also, the v0.3.0 branch has the ability to use source filtering, which is particularly good for large volumes of data, when not all columns need to be returned. I'm intending to get the v0.3.0 release out before the end of the year.

**Comment by blevid2** [comment]
No strong opinions here.  I did notice that the solution you're currently pursuing checks the tagline, which I think is not a great way to validate the endpoint.

Based on how I read the code it looked like `valid_url` was only intended to check for a well-formed endpoint URI.

With the changes you've committed to your pull request, it looks like you're now verifying the functionality of the endpoint, and also trying to verify that the endpoint is indeed elasticsearch.  Verifying the functionality of the endpoint seems like a good alternative to checking for well-formed URIs, though it is fundamentally different from the original function.  

*However*, I think the tagline check `if (response_parsed$tagline == "You Know, for Search")` is not useful, and is incredibly fragile.  Not only does the check assume that Elasticsearch will continue using that tagline, the check is case sensitive, and the tagline is easily emulated by non-Elasticsearch systems.  *Succinctly* the tagline check doesn't really serve a purpose, since the tagline is neither a unique nor persistent identifier for Elasticsearch.

**Comment by blevid2** [comment]
Thanks for taking our feedback into consideration.

**Comment by AlexIoannides** [comment]
Merged and submitted to CRAN.
